### ISSUE TITLE
B::Deparse check is useless

### ISSUE THREAD

**Issue by zdm** [steve-m-hay/Filter-Crypto#1]
Hi,
Nothing is preventing me to load Filter::Crypto::Decrypt and, then, B::Deparse before run encrypted script:

Decrypt.pm
```
package Decrypt;
require Filter::Crypto::Decrypt;
require B::Deparse;
1;
__END__
```

```
$ perl -M"Decrypt" ./encypted.pl
```
So, this protection is useless and easily can be avoided.

But it prevents to load encrypted modules after B was loaded by some package.
For example, Sub::Quote using B.
This just adding headache, but not extra protection.

I think, that check for B::Deparse presence can be removed.

**Comment by steve-m-hay** [comment]
Closing this issue: See comments on https://rt.cpan.org/Ticket/Display.html?id=102788.
