### ISSUE TITLE
openssl 3.0.1

### ISSUE THREAD

**Issue by jm2307** [steve-m-hay/Filter-Crypto#7]
Hi,
I'm not able to install Filter-Cryto in Rockylinux 9
which uses openssl 3.0.1.

Thanks
JDM

**Comment by steve-m-hay** [comment]
Apologies. That's probably because I haven't got round to applying this PR
yet: https://github.com/steve-m-hay/Filter-Crypto/pull/6

I will get that done as soon as possible. If you're able to test that the
patch works in the meantime then that would be cool to know.

**Comment by jm2307** [comment]
Hi Steve,
I tested the patch, it work fine.
Thanks
JDM
